[build]
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"

[build.environment]
  # Node version to use
  NODE_VERSION = "18"

# Redirect rules for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

